version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: event_management
    ports:
      - ${DB_PORT}:3306
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - event_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
    container_name: go_event_management
    restart: on-failure:3
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - event_network

  testservice:
    container_name: testservice
    build:
      context: postman_collection
      dockerfile: test.Dockerfile
    image: tuhin47/testservice:golang
    depends_on:
      app:
        condition: service_healthy
    networks:
      - event_network
networks:
  event_network:
    driver: bridge

volumes:
  db_data: